- name: cart
  hosts: cart
  tasks: 
  - name: disbling older version nodejs and installin new
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent    
    
  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading content to created directory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: unzipping content
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: installing dependencies
    ansible.builtin.command:  npm install
    args:
      chdir: /app


  - name: configuring cart.service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: load the service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enabling and starting cart
    ansible.builtin.service:
      state: restarted