- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling old nodejs and enable new version
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present 