- name: monogodb
  hosts: mongodb
  become: yes
  tasks: 
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: mongodb server start and enable
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: mongodb server start and enable
    ansible.builtin.service:
      name: mongod
      state: restarted

  - name: copy catalogue service
    ansible.builtin.copy:
      name: catalogue.service
      src: /etc/systemd/system/catalogue.service

  - name: daemon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true

   #start after the data is loaded   

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
      
  - name: install mongodb client
    ansible.builtin.package:
      name: mogodb-org-shell
      state: present
